version: '3'

networks:
  edumentors_laravel:


services:

  mysql:
    image: mariadb:10.5.8
    container_name: edumentors_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - edumentors_laravel

  phpmyadmin:
    container_name: edumentors_admin
    depends_on:
      - mysql
    # image: phpmyadmin/phpmyadmin
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '8086:80'
    env_file:
      - .env
    networks:
      - edumentors_laravel

  redis:
    image: redis:alpine
    container_name: edumentors_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - edumentors_laravel